version: '3.8'

services:
  vault:
    image: vault:1.13.3
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_ADDR: http://0.0.0.0:8200
    command: "server -dev -dev-root-token-id=root"
    volumes:
      - ./vault/data:/vault/data
